import { PermissionActionEnum } from "src/app/core/enums/permission-action-enum";
import { MenuItem } from "./menu.model";
import { SchoolMenuEnum } from "src/app/core/enums/menu-enum";

export const MENU: MenuItem[] = [
  {
    id: SchoolMenuEnum.General,
    label: "MENUITEMS.GENERAL.TEXT",
    isTitle: true,
  },
  {
    id: SchoolMenuEnum.Dashboard,
    label: "MENUITEMS.DASHBOARD.TEXT",
    icon: " ri-home-3-line",
    link: "/",
    permission: PermissionActionEnum.School_ViewDashboard,
  },
  {
    id: SchoolMenuEnum.Analytics,
    label: "MENUITEMS.ANALYTICS.TEXT",
    icon: "ri-line-chart-line",
    link: "/school/analytics",
    permission: PermissionActionEnum.School_ViewAnalytics,
  },
  {
    id: SchoolMenuEnum.Configuration,
    label: "MENUITEMS.CONFIGURATION.TEXT",
    icon: " ri-settings-3-line",
    isCollapsed: true,
    permission: PermissionActionEnum.School_ViewConfiguration,
    subItems: [
      {
        id: SchoolMenuEnum.SystemSettings,
        label: "MENUITEMS.CONFIGURATION.LIST.SYSTEMSETTINGS",
        parentId: SchoolMenuEnum.Configuration,
        link: "/school/configuration/system",
        permission: PermissionActionEnum.School_ManageConfiguration,
      },
      {
        id: SchoolMenuEnum.School,
        label: "MENUITEMS.CONFIGURATION.LIST.SCHOOL",
        parentId: SchoolMenuEnum.Configuration,
        link: "/school/configuration/school",
        permission: PermissionActionEnum.School_ManageConfiguration,
      },
      {
        id: SchoolMenuEnum.Academics,
        label: "MENUITEMS.CONFIGURATION.LIST.ACADEMICS",
        icon: " ri-calendar-2-line",
        isCollapsed: true,
        permission: PermissionActionEnum.School_ManageConfiguration,
        subItems: [
          {
            id: SchoolMenuEnum.AcademicYear,
            label: "MENUITEMS.ACADEMICS.LIST.ACADEMICYEARS",
            parentId: SchoolMenuEnum.Academics,
            link: "/school/configuration/academics/academic-years",
            permission: PermissionActionEnum.School_ManageConfiguration,
          },
          {
            id: SchoolMenuEnum.AcademicTerm,
            label: "MENUITEMS.ACADEMICS.LIST.ACADEMICTERMS",
            parentId: SchoolMenuEnum.Academics,
            link: "/school/configuration/academics/academic-terms",
            permission: PermissionActionEnum.School_ManageConfiguration,
          },
          {
            id: SchoolMenuEnum.AcademicPeriod,
            label: "MENUITEMS.ACADEMICS.LIST.ACADEMICPERIODS",
            parentId: SchoolMenuEnum.Academics,
            link: "/school/configuration/academics/academic-periods",
            permission: PermissionActionEnum.School_ManageConfiguration,
          },
          {
            id: SchoolMenuEnum.RollOver,
            label: "MENUITEMS.ACADEMICS.LIST.ROLLOVER",
            parentId: SchoolMenuEnum.Academics,
            link: "/school/configuration/academics/rollover",
            permission: PermissionActionEnum.School_ManageConfiguration,
         },
        ],
      },
      {
        id: SchoolMenuEnum.Admission,
        label: "MENUITEMS.CONFIGURATION.LIST.ADMISSION",
        parentId: SchoolMenuEnum.Configuration,
        link: "/school/configuration/admission",
        permission: PermissionActionEnum.School_ManageConfiguration,
      },
      {
        id: SchoolMenuEnum.ExamTypes,
        label: "MENUITEMS.CONFIGURATION.LIST.EXAMTYPES",
        parentId: SchoolMenuEnum.Configuration,
        link: "/school/configuration/exam-types",
        permission: PermissionActionEnum.School_ManageConfiguration,
      },
      {
        id: SchoolMenuEnum.Sections,
        label: "MENUITEMS.CONFIGURATION.LIST.SECTIONS",
        parentId: SchoolMenuEnum.Configuration,
        link: "/school/configuration/sections",
        permission: PermissionActionEnum.School_ManageConfiguration,
      },
      {
        id: SchoolMenuEnum.Subjects,
        label: "MENUITEMS.CONFIGURATION.LIST.SUBJECTS",
        parentId: SchoolMenuEnum.Configuration,
        link: "/school/configuration/subjects",
        permission: PermissionActionEnum.School_ManageConfiguration,
      },
      {
        id: SchoolMenuEnum.Classes,
        label: "MENUITEMS.CONFIGURATION.LIST.CLASSES",
        parentId: SchoolMenuEnum.Configuration,
        link: "/school/configuration/classes",
        permission: PermissionActionEnum.School_ManageConfiguration,
      },
      {
        id: SchoolMenuEnum.Courses,
        label: "MENUITEMS.CONFIGURATION.LIST.COURSES",
        parentId: SchoolMenuEnum.Configuration,
        link: "/school/configuration/courses",
        permission: PermissionActionEnum.School_ManageConfiguration,
      },
      {
        id: SchoolMenuEnum.Grading,
        label: "MENUITEMS.CONFIGURATION.LIST.GRADING",
        parentId: SchoolMenuEnum.Configuration,
        isCollapsed: true,
        permission: PermissionActionEnum.School_ManageConfiguration,
        subItems: [
          {
            id: SchoolMenuEnum.GradingSystems,
            label: "MENUITEMS.GRADING.LIST.GRADINGSYSTEMS",
            link: "/school/configuration/grading/grading-systems",
            parentId: SchoolMenuEnum.Grading,
            permission: PermissionActionEnum.School_ManageConfiguration,
          },
          {
            id: SchoolMenuEnum.GradeSetup,
            label: "MENUITEMS.GRADING.LIST.GRADESETUP",
            link: "/school/configuration/grading/grade-setup",
            parentId: SchoolMenuEnum.Grading,
            permission: PermissionActionEnum.School_ManageConfiguration,
          },
        ],
      },
    ],
  },
  {
    id: SchoolMenuEnum.Reporting,
    label: "MENUITEMS.REPORTING.TEXT",
    isTitle: true,
  },

  {
    id: SchoolMenuEnum.ResultReports,
    label: "MENUITEMS.RESULTREPORTS.TEXT",
    icon: "ri-file-list-3-line",
    isCollapsed: true,
    permission: PermissionActionEnum.School_ManageReports,
    subItems: [
      {
        id: SchoolMenuEnum.ReportCards,
        label: "MENUITEMS.RESULTREPORTS.LIST.REPORTCARDS",
        parentId: SchoolMenuEnum.ResultReports,
        link: "/school/reporting/result-reports/report-cards",
        permission: PermissionActionEnum.School_ManageReports,
      },
      {
        id: SchoolMenuEnum.Transcripts,
        label: "MENUITEMS.RESULTREPORTS.LIST.TRANSCRIPTS",
        parentId: SchoolMenuEnum.ResultReports,
        link: "/school/reporting/result-reports/transcripts",
        permission: PermissionActionEnum.School_ManageReports,
      },
      {
        id: SchoolMenuEnum.MasterSheets,
        label: "MENUITEMS.RESULTREPORTS.LIST.MASTERSHEETS",
        parentId: SchoolMenuEnum.ResultReports,
        link: "/school/reporting/result-reports/master-sheets",
        permission: PermissionActionEnum.School_ManageReports,
      },
    ],
  },

  {
    id: SchoolMenuEnum.Core,
    label: "MENUITEMS.CORE.TEXT",
    isTitle: true,
  },
  {
    id: SchoolMenuEnum.Personnel,
    label: "MENUITEMS.PERSONNEL.TEXT",
    icon: "ri-admin-line",
    isCollapsed: true,
    permission: PermissionActionEnum.School_ViewPersonnel,
    subItems: [
      {
        id: SchoolMenuEnum.Employees,
        label: "MENUITEMS.PERSONNEL.LIST.EMPLOYEES",
        parentId: SchoolMenuEnum.Personnel,
        link: "/school/personnel/employees",
        permission: PermissionActionEnum.School_ViewPersonnel,
      },
      {
        id: SchoolMenuEnum.Teachers,
        label: "MENUITEMS.PERSONNEL.LIST.TEACHERS",
        parentId: SchoolMenuEnum.Personnel,
        link: "/school/personnel/teachers",
        permission: PermissionActionEnum.School_ViewPersonnel,
      },
    ],
  },
  {
    id: SchoolMenuEnum.Students,
    label: "MENUITEMS.STUDENTS.TEXT",
    icon: "ri-team-line",
    isCollapsed: true,
    permission: PermissionActionEnum.School_ViewStudents,
    subItems: [
      {
        id: SchoolMenuEnum.StudentRegistration,
        label: "MENUITEMS.STUDENTS.LIST.REGISTRATION",
        parentId: SchoolMenuEnum.Students,
        link: "/school/students/student-registration",
        permission: PermissionActionEnum.School_ManageStudents,
      },
      {
        id: SchoolMenuEnum.StudentEnrollments,
        label: "MENUITEMS.STUDENTS.LIST.ENROLLMENTS",
        parentId: SchoolMenuEnum.Students,
        link: "/school/students/student-enrollments",
        permission: PermissionActionEnum.School_ManageStudents,
      },
    ],
  },
  {
    id: SchoolMenuEnum.Parents,
    label: "MENUITEMS.PARENTS.TEXT",
    icon: " ri-parent-line",
    link: "/school/parents",
    permission: PermissionActionEnum.School_ManageParents,
  },
  {
    id: SchoolMenuEnum.Attendance,
    label: "MENUITEMS.ATTENDANCE.TEXT",
    icon: "ri-user-voice-line",
    isCollapsed: true,
    permission: PermissionActionEnum.School_ViewAttendance,
    subItems: [
      {
        id: SchoolMenuEnum.StudentAttendance,
        label: "MENUITEMS.ATTENDANCE.LIST.STUDENTATTENDANCE",
        parentId: SchoolMenuEnum.Attendance,
        link: "/school/attendance/student-attendance",
        permission: PermissionActionEnum.School_ViewAttendance,
      },
      {
        id: SchoolMenuEnum.TeacherAttendance,
        label: "MENUITEMS.ATTENDANCE.LIST.TEACHERATTENDANCE",
        parentId: SchoolMenuEnum.Attendance,
        link: "/school/attendance/teacher-attendance",
        permission: PermissionActionEnum.School_ViewAttendance,
      },
    ],
  },

  {
    id: SchoolMenuEnum.Exams,
    label: "MENUITEMS.EXAMS.TEXT",
    icon: "ri-pencil-ruler-line",
    link: "/school/exams",
    permission: PermissionActionEnum.School_ViewExams,
  },

  {
    id: SchoolMenuEnum.Results,
    label: "MENUITEMS.RESULTS.TEXT",
    icon: " ri-pages-line",
    isCollapsed: true,
    permission: PermissionActionEnum.School_ViewResults,
    subItems: [
      {
        id: SchoolMenuEnum.RegisterResults,
        label: "MENUITEMS.RESULTS.LIST.REGISTERRESULTS",
        parentId: SchoolMenuEnum.Results,
        link: "/school/results/register-results",
        permission: PermissionActionEnum.School_RegisterResults,
      },
      {
        id: SchoolMenuEnum.ResultHistory,
        label: "MENUITEMS.RESULTS.LIST.RESULTHISTORY",
        parentId: SchoolMenuEnum.Results,
        link: "/school/results/result-history",
        permission: PermissionActionEnum.School_ManageResultHistory,
      },
    ],
  },
  {
    id: SchoolMenuEnum.Library,
    label: "MENUITEMS.LIBRARY.TEXT",
    icon: "ri-book-2-fill",
    isCollapsed: true,
    permission: PermissionActionEnum.School_ViewLibrary,
    link: "/school/library",
  },
  {
    id: SchoolMenuEnum.Inventory,
    label: "MENUITEMS.INVENTORY.TEXT",
    icon: " ri-shopping-cart-2-fill",
    isCollapsed: true,
    permission: PermissionActionEnum.School_ViewInventory,
    link: "/school/inventory",
  },
  {
    id: SchoolMenuEnum.Accounting,
    label: "MENUITEMS.ACCOUNTING.TEXT",
    icon: "ri-scales-line",
    isCollapsed: true,
    permission: PermissionActionEnum.School_ViewAccounting,
    subItems: [
      {
        id: SchoolMenuEnum.ChartOfAccounts,
        label: "MENUITEMS.ACCOUNTING.LIST.CHARTOFACCOUNTS",
        parentId: SchoolMenuEnum.Bursary,
        link: "/school/accounting/chart-of-accounts",
        permission: PermissionActionEnum.School_ManageAccounting,
      },
      {
        id: SchoolMenuEnum.Journals,
        label: "MENUITEMS.ACCOUNTING.LIST.JOURNALS",
        parentId: SchoolMenuEnum.Bursary,
        link: "/school/accounting/journals",
        permission: PermissionActionEnum.School_ManageAccounting,
      },
    ],
  },

  {
    id: SchoolMenuEnum.Finance,
    label: "MENUITEMS.FINANCE.TEXT",
    icon: " ri-hand-coin-fill",
    isCollapsed: true,
    permission: PermissionActionEnum.School_ViewFinance,
    subItems: [
      {
        id: SchoolMenuEnum.Fees,
        label: "MENUITEMS.FINANCE.LIST.FEES",
        parentId: SchoolMenuEnum.Finance,
        link: "/school/finance/fees",
        permission: PermissionActionEnum.School_ManageFinances,
      },
      {
        id: SchoolMenuEnum.Subscription,
        label: "MENUITEMS.FINANCE.LIST.SUBSCRIPTIONS",
        parentId: SchoolMenuEnum.Finance,
        link: "/school/finance/subscriptions",
        permission: PermissionActionEnum.School_ManageSubscription,
      }
      // {
      //   id: SchoolMenuEnum.Fees,
      //   label: "MENUITEMS.FINANCE.LIST.FEES",
      //   icon: "ri-wallet-line",
      //   isCollapsed: true,
      //   parentId: SchoolMenuEnum.Finance,
      //   permission: PermissionActionEnum.School_ManageFinances,
      //   subItems: [
      //     {
      //       id: SchoolMenuEnum.FeeTypes,
      //       label: "MENUITEMS.FEES.LIST.FEETYPES",
      //       parentId: SchoolMenuEnum.Fees,
      //       link: "/school/finance/fee-types",
      //       permission: PermissionActionEnum.School_ManageFinances,
      //     },
      //     {
      //       id: SchoolMenuEnum.ClassFeeTypes,
      //       label: "MENUITEMS.FEES.LIST.CLASSFEETYPES",
      //       parentId: SchoolMenuEnum.Fees,
      //       link: "/school/finance/class-fee-types",
      //       permission: PermissionActionEnum.School_ManageFinances,
      //     },
      //     {
      //       id: SchoolMenuEnum.StudentFeeTypes,
      //       label: "MENUITEMS.FEES.LIST.STUDENTFEETYPES",
      //       parentId: SchoolMenuEnum.Fees,
      //       link: "/school/finance/student-fee-types",
      //       permission: PermissionActionEnum.School_ManageFinances,
      //     },
      //   ],
      // },
    ],
  },
  {
    id: SchoolMenuEnum.Bursary,
    label: "MENUITEMS.BURSARY.TEXT",
    icon: "ri-bank-line",
    isCollapsed: true,
    permission: PermissionActionEnum.School_ViewBursary,
    subItems: [
      {
        id: SchoolMenuEnum.CashDesk,
        label: "MENUITEMS.BURSARY.LIST.CASHDESK",
        parentId: SchoolMenuEnum.Bursary,
        link: "/school/bursary/cash-desk",
        permission: PermissionActionEnum.School_ManageBursary,
      },
      {
        id: SchoolMenuEnum.PaymentAchieve,
        label: "MENUITEMS.BURSARY.LIST.PAYMENTARCHIVE", 
        parentId: SchoolMenuEnum.Bursary,
        link: "/school/bursary/payment-archive",
        permission: PermissionActionEnum.School_ManageBursary,
      },
    ],
  },
  {
    id: SchoolMenuEnum.Boarding,
    label: "MENUITEMS.BOARDING.TEXT",
    icon: "ri-community-line",
    isCollapsed: true,
    permission: PermissionActionEnum.School_ViewBoarding,
    link: "/school/boarding",
  },

  {
    id: SchoolMenuEnum.Transportation,
    label: "MENUITEMS.TRANSPORTATION.TEXT",
    icon: "ri-bus-line",
    isCollapsed: true,
    permission: PermissionActionEnum.School_ViewTransportation,
    link: "/school/transportation",
  },

  {
    id: SchoolMenuEnum.Users,
    label: "MENUITEMS.USERS.TEXT",
    icon: "ri-team-line",
    isCollapsed: true,
    permission: PermissionActionEnum.School_ViewUsers,
    subItems: [
      {
        id: SchoolMenuEnum.Roles,
        label: "MENUITEMS.USERS.LIST.ROLES",
        parentId: SchoolMenuEnum.Users,
        link: "/school/users/roles",
        permission: PermissionActionEnum.School_ManageUsers,
      },
      {
        id: SchoolMenuEnum.ManageUsers,
        label: "MENUITEMS.USERS.LIST.MANAGEUSERS",
        parentId: SchoolMenuEnum.Users,
        link: "/school/users/manage-users",
        permission: PermissionActionEnum.School_ManageUsers,
      },
      {
        id: SchoolMenuEnum.ManageUsers,
        label: "MENUITEMS.USERS.LIST.AUDITLOGS",
        parentId: SchoolMenuEnum.AuditLogs,
        link: "/school/users/logs",
        permission: PermissionActionEnum.School_ManageUsers,
      },
    ],
  },
  {
    id: SchoolMenuEnum.Files,
    label: "MENUITEMS.FILES.TEXT",
    icon: "ri-folder-2-line",
    isCollapsed: true,
    permission: PermissionActionEnum.School_ViewFiles,
    link: "/school/files",
  }
];
