import { PermissionActionEnum } from "src/app/core/enums/permission-action-enum";
import { MenuItem } from "./menu.model";
import { SchoolMenuEnum } from "src/app/core/enums/menu-enum";

export const MENU: MenuItem[] = [
  {
    id: SchoolMenuEnum.General,
    label: "MENUITEMS.GENERAL.TEXT",
    isTitle: true,
  },
  {
    id: SchoolMenuEnum.Dashboard,
    label: "MENUITEMS.DASHBOARD.TEXT",
    icon: " ri-home-3-line",
    link: "/",
    permission: PermissionActionEnum.School_ViewDashboard,
  },
  {
    id: SchoolMenuEnum.Analytics,
    label: "MENUITEMS.ANALYTICS.TEXT",
    icon: "ri-line-chart-line",
    link: "/analytics",
    permission: PermissionActionEnum.School_ViewAnalytics,
  },
  {
    id: SchoolMenuEnum.Configuration,
    label: "MENUITEMS.CONFIGURATIONS.TEXT",
    icon: " ri-settings-3-line",
    isCollapsed: true,
    permission: PermissionActionEnum.School_ViewConfiguration,
    subItems: [
      {
        id: SchoolMenuEnum.School,
        label: "MENUITEMS.CONFIGURATIONS.LIST.SCHOOL",
        parentId: SchoolMenuEnum.Configuration,
        link: "/configuration/school",
        permission: PermissionActionEnum.School_ManageConfiguration,
      },
      {
        id: SchoolMenuEnum.Admission,
        label: "MENUITEMS.CONFIGURATIONS.LIST.ADMISSION",
        parentId: SchoolMenuEnum.Configuration,
        link: "/configuration/admission",
        permission: PermissionActionEnum.School_ManageConfiguration,
      },
      {
        id: SchoolMenuEnum.Sections,
        label: "MENUITEMS.CONFIGURATIONS.LIST.SECTIONS",
        parentId: SchoolMenuEnum.Configuration,
        link: "/configuration/sections",
        permission: PermissionActionEnum.School_ManageConfiguration,
      },
      {
        id: SchoolMenuEnum.ExamTypes,
        label: "MENUITEMS.CONFIGURATIONS.LIST.EXAMTYPES",
        parentId: SchoolMenuEnum.Configuration,
        link: "/configuration/exam-types",
        permission: PermissionActionEnum.School_ManageConfiguration,
      },
      {
        id: SchoolMenuEnum.Subjects,
        label: "MENUITEMS.CONFIGURATIONS.LIST.SUBJECTS",
        parentId: SchoolMenuEnum.Configuration,
        link: "/configuration/subjects",
        permission: PermissionActionEnum.School_ManageConfiguration,
      },
      {
        id: SchoolMenuEnum.Courses,
        label: "MENUITEMS.CONFIGURATIONS.LIST.COURSES",
        parentId: SchoolMenuEnum.Configuration,
        link: "/configuration/courses",
        permission: PermissionActionEnum.School_ManageConfiguration,
      },
      {
        id: SchoolMenuEnum.Grading,
        label: "MENUITEMS.CONFIGURATIONS.LIST.GRADING",
        parentId: SchoolMenuEnum.Configuration,
        isCollapsed: true,
        permission: PermissionActionEnum.School_ManageConfiguration,
        subItems: [
          {
            id: SchoolMenuEnum.GradingSystems,
            label: "MENUITEMS.GRADING.LIST.GRADINGSYSTEMS",
            link: "/configuration/grading/grading-systems",
            parentId: SchoolMenuEnum.Grading,
            permission: PermissionActionEnum.School_ManageConfiguration,
          },
          {
            id: SchoolMenuEnum.GradeSetup,
            label: "MENUITEMS.GRADING.LIST.GRADESETUP",
            link: "/configuration/grading/grade-setup",
            parentId: SchoolMenuEnum.Grading,
            permission: PermissionActionEnum.School_ManageConfiguration,
          },
        ],
      },
      {
        id: SchoolMenuEnum.Classes,
        label: "MENUITEMS.CONFIGURATIONS.LIST.CLASSES",
        parentId: SchoolMenuEnum.Configuration,
        link: "/configuration/classes",
        permission: PermissionActionEnum.School_ManageConfiguration,
      },
      {
        id: SchoolMenuEnum.Academics,
        label: "MENUITEMS.CONFIGURATIONS.LIST.ACADEMICS",
        icon: " ri-calendar-2-line",
        isCollapsed: true,
        permission: PermissionActionEnum.School_ManageConfiguration,
        subItems: [
          {
            id: SchoolMenuEnum.AcademicYear,
            label: "MENUITEMS.ACADEMICS.LIST.ACADEMICYEARS",
            parentId: SchoolMenuEnum.Academics,
            link: "/configuration/academics/academic-years",
            permission: PermissionActionEnum.School_ManageConfiguration,
          },
          {
            id: SchoolMenuEnum.AcademicTerm,
            label: "MENUITEMS.ACADEMICS.LIST.ACADEMICTERMS",
            parentId: SchoolMenuEnum.Academics,
            link: "/configuration/academics/academic-terms",
            permission: PermissionActionEnum.School_ManageConfiguration,
          },
          {
            id: SchoolMenuEnum.AcademicPeriod,
            label: "MENUITEMS.ACADEMICS.LIST.ACADEMICPERIODS",
            parentId: SchoolMenuEnum.Academics,
            link: "/configuration/academics/academic-periods",
            permission: PermissionActionEnum.School_ManageConfiguration,
          },
        ],
      },
    ],
  },
  {
    id: SchoolMenuEnum.Reporting,
    label: "MENUITEMS.REPORTING.TEXT",
    isTitle: true,
  },
  {
    id: SchoolMenuEnum.ReportCards,
    label: "MENUITEMS.REPORTS.LIST.REPORTCARDS",
    parentId: SchoolMenuEnum.Reports,
    link: "/reporting/report-cards",
    icon: "ri-file-paper-2-line",
    permission: PermissionActionEnum.School_ManageReports,
  },
  {
    id: SchoolMenuEnum.Transcripts,
    label: "MENUITEMS.REPORTS.LIST.TRANSCRIPTS",
    parentId: SchoolMenuEnum.Reports,
    link: "/reporting/transcripts",
    icon: " ri-file-list-3-line",
    permission: PermissionActionEnum.School_ManageReports,
  },
  {
    id: SchoolMenuEnum.MasterSheets,
    label: "MENUITEMS.REPORTS.LIST.MASTERSHEETS",
    parentId: SchoolMenuEnum.Reports,
    link: "/reporting/master-sheets",
    icon: "ri-survey-line",
    permission: PermissionActionEnum.School_ManageReports,
  },

  {
    id: SchoolMenuEnum.Core,
    label: "MENUITEMS.CORE.TEXT",
    isTitle: true,
  },
  {
    id: SchoolMenuEnum.Personnel,
    label: "MENUITEMS.PERSONNEL.TEXT",
    icon: "ri-admin-line",
    isCollapsed: true,
    permission: PermissionActionEnum.School_ViewPersonnel,
    subItems: [
      {
        id: SchoolMenuEnum.Employees,
        label: "MENUITEMS.PERSONNEL.LIST.EMPLOYEES",
        parentId: SchoolMenuEnum.Personnel,
        link: "/personnel/employees",
        permission: PermissionActionEnum.School_ViewPersonnel,
      },
      {
        id: SchoolMenuEnum.Teachers,
        label: "MENUITEMS.PERSONNEL.LIST.TEACHERS",
        parentId: SchoolMenuEnum.Personnel,
        link: "/personnel/teachers",
        permission: PermissionActionEnum.School_ViewPersonnel,
      },
    ],
  },
  {
    id: SchoolMenuEnum.Students,
    label: "MENUITEMS.STUDENTS.TEXT",
    icon: "ri-team-line",
    isCollapsed: true,
    permission: PermissionActionEnum.School_ViewStudents,
    subItems: [
      {
        id: SchoolMenuEnum.StudentRegistration,
        label: "MENUITEMS.STUDENTS.LIST.REGISTRATION",
        parentId: SchoolMenuEnum.Students,
        link: "/students/student-registration",
        permission: PermissionActionEnum.School_ManageStudents,
      },
      {
        id: SchoolMenuEnum.StudentEnrollments,
        label: "MENUITEMS.STUDENTS.LIST.ENROLLMENTS",
        parentId: SchoolMenuEnum.Students,
        link: "/students/student-enrollments",
        permission: PermissionActionEnum.School_ManageStudents,
      },
    ],
  },
  {
    id: SchoolMenuEnum.Parents,
    label: "MENUITEMS.PARENTS.TEXT",
    icon: " ri-parent-line",
    link: "/parents",
    permission: PermissionActionEnum.School_ManageParents,
  },
  {
    id: SchoolMenuEnum.Attendance,
    label: "MENUITEMS.ATTENDANCE.TEXT",
    icon: "ri-user-voice-line",
    isCollapsed: true,
    permission: PermissionActionEnum.School_ViewAttendance,
    subItems: [
      {
        id: SchoolMenuEnum.StudentAttendance,
        label: "MENUITEMS.ATTENDANCE.LIST.STUDENTATTENDANCE",
        parentId: SchoolMenuEnum.Attendance,
        link: "/attendance/student-attendance",
        permission: PermissionActionEnum.School_ViewAttendance,
      },
      {
        id: SchoolMenuEnum.TeacherAttendance,
        label: "MENUITEMS.ATTENDANCE.LIST.TEACHERATTENDANCE",
        parentId: SchoolMenuEnum.Attendance,
        link: "/attendance/teacher-attendance",
        permission: PermissionActionEnum.School_ViewAttendance,
      },
    ],
  },

  {
    id: SchoolMenuEnum.Exams,
    label: "MENUITEMS.EXAMS.TEXT",
    icon: "ri-pencil-ruler-line",
    link: "/exams",
    permission: PermissionActionEnum.School_ViewExams,
  },

  {
    id: SchoolMenuEnum.Results,
    label: "MENUITEMS.RESULTS.TEXT",
    icon: " ri-pages-line",
    isCollapsed: true,
    permission: PermissionActionEnum.School_ViewResults,
    subItems: [
      {
        id: SchoolMenuEnum.RegisterResults,
        label: "MENUITEMS.RESULTS.LIST.REGISTERRESULTS",
        parentId: SchoolMenuEnum.Results,
        link: "/results/register-results",
        permission: PermissionActionEnum.School_RegisterResults,
      },
      {
        id: SchoolMenuEnum.ResultHistory,
        label: "MENUITEMS.RESULTS.LIST.RESULTHISTORY",
        parentId: SchoolMenuEnum.Results,
        link: "/results/result-history",
        permission: PermissionActionEnum.School_ManageResultHistory,
      },
    ],
  },
  {
    id: SchoolMenuEnum.Library,
    label: "MENUITEMS.LIBRARY.TEXT",
    icon: "ri-book-2-fill",
    isCollapsed: true,
    permission: PermissionActionEnum.School_ViewLibrary,
    link: "/library",
  },
  {
    id: SchoolMenuEnum.Inventory,
    label: "MENUITEMS.INVENTORY.TEXT",
    icon: " ri-shopping-cart-2-fill",
    isCollapsed: true,
    permission: PermissionActionEnum.School_ViewInventory,
    link: "/inventory",
  },

  {
    id: SchoolMenuEnum.Finance,
    label: "MENUITEMS.FINANCE.TEXT",
    icon: " ri-hand-coin-fill",
    isCollapsed: true,
    permission: PermissionActionEnum.School_ViewFinance,
    subItems: [
      {
        id: SchoolMenuEnum.Subscription,
        label: "MENUITEMS.FINANCE.LIST.SUBSCRIPTIONS",
        parentId: SchoolMenuEnum.Finance,
        link: "/finance/subscriptions",
        permission: PermissionActionEnum.School_ManageSubscription,
      },
    ],
  },
  {
    id: SchoolMenuEnum.Boarding,
    label: "MENUITEMS.BOARDING.TEXT",
    icon: "ri-community-line",
    isCollapsed: true,
    permission: PermissionActionEnum.School_ViewBoarding,
    link: "/boarding",
  },

  {
    id: SchoolMenuEnum.Transportation,
    label: "MENUITEMS.TRANSPORTATION.TEXT",
    icon: "ri-bus-line",
    isCollapsed: true,
    permission: PermissionActionEnum.School_ViewTransportation,
    link: "/transportation",
  },

  {
    id: SchoolMenuEnum.Users,
    label: "MENUITEMS.USERS.TEXT",
    icon: "ri-team-line",
    isCollapsed: true,
    permission: PermissionActionEnum.School_ViewUsers,
    subItems: [
      {
        id: SchoolMenuEnum.Roles,
        label: "MENUITEMS.USERS.LIST.ROLES",
        parentId: SchoolMenuEnum.Users,
        link: "/users/roles",
        permission: PermissionActionEnum.School_ManageUsers,
      },
      {
        id: SchoolMenuEnum.ManageUsers,
        label: "MENUITEMS.USERS.LIST.MANAGEUSERS",
        parentId: SchoolMenuEnum.Users,
        link: "/users/manage-users",
        permission: PermissionActionEnum.School_ManageUsers,
      },
    ],
  },
];
